### ISSUE TITLE
Modifier les libellés des boutons 

### ISSUE THREAD

**Issue by vdegrandpre** [jabberbees/semantic-ui-react-formik#1]
Bonjour,

Librairie fantastique. Merci. Comment peut-on modifier les libellés des boutons 'Next', 'Previous', 'Submit' facilement ? Avez-vous quelconque disposition à cet effet ?

Merci,
VdeG

![Capture du 2019-06-09 15-13-33](https://user-images.githubusercontent.com/3855975/59163029-37c18600-8ac9-11e9-9c8f-b815fe3f50f1.png)

**Comment by eboutin** [comment]
Merci pour le commentaire. Il y a un exemple de customisation des libellés dans example/src/MyForm.js :
`
    <Wizard
      initialValues={...}
      buttonLabels={{
        previous: "PREVIOUS",
        next: "NEXT",
        submit: "SUBMIT"
      }}
     ...
`
Est-ce que cela répond à votre besoin ?

**Comment by vdegrandpre** [comment]
Oui, c'est exactement ça. Merci ! :+1:
