### ISSUE TITLE
How do I have custom buttons in Wizard pages other than previous, next and Submit. 

### ISSUE THREAD

**Issue by bhukailas** [jabberbees/semantic-ui-react-formik#2]
the use case is

I have 10 screens and I would like to jump from 4th to 9th and 9th to 3rd pages when user clicks on a particular button... along with this I would like to do some validation and make rest API calls to server and validate page fields and give back control to user

Could you please mail me @ bhukailas448@gmail.com about your availability as I would like to discuss few things with you

**Comment by eboutin** [comment]
Hi, the example provided shows how to disable default buttons and use custom ones with custom actions.
I use this library in a business web app with API calls at each step.
I perform some tracking API calls in componentDidMount() on each page and also from the custom buttons onClick handler.
Sorry I'm too busy at the moment to discuss in more details.
Please keep on posting your questions here I will answer as soon as I can

**Comment by bhukailas** [comment]
Could you please help me in writing code to jump from SelectionPage to Submit directly? For example if there are 10 pages ... I am want to jump from page **x** to page **y**  and vice versa.

Also I would like to populate data for page **x** from a API call which I make in page **x-1**

in my business code I have more buttons other than **Prev, Next and Submit**, upon clicking those I will validate user entered data and fetch data for subsequent pages as well and populate that data as user moves to those pages. So I kind of needed some global state for all of those pages.

Please provide some sample code for above requirement

**Comment by eboutin** [comment]
Sorry I had no time to reply earlier. I think I answered your question. Your latest comment is specific use case related to your application. I'll close the issue.
